kind: Deployment
apiVersion: apps/v1
metadata:
  name: deep-thought
  namespace: deep-thought-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-thought
  template:
    metadata:
      labels:
        app: deep-thought
        deployment: deep-thought
    spec:
      volumes:
        - name: deepthoughtjson
          secret:
            secretName: google-application-credentials
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: deep-thought
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: deepthoughtjson
              readOnly: true
              mountPath: /etc/42
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: deep-thought-config
            - secretRef:
                name: deep-thought-secrets
          image: >-
            image-registry.openshift-image-registry.svc:5000/deep-thought-dev/deep-thought@sha256:068de3920f7bb0006a4ae60927536bd5e7c8181e750814bd16b516958ed31ec7
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  