kind: Secret
apiVersion: v1
metadata:
  name: deep-thought-secrets
  # namespace: deep-thought-dev
  annotations:
    controller.devfile.io/mount-as: env
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'