kind: ConfigMap
apiVersion: v1
metadata:
  name: deep-thought-config
  #namespace: deep-thought-dev
  annotations:
    controller.devfile.io/mount-as: env
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
data:
  PYTHONPATH: /
  SPENDING_WARNING_PCT: '0.8'
  OPENAI_MODEL_PRICE: '0.000003'
  VERTEX_MODEL_VERSION: v1
  GOOGLE_APPLICATION_CREDENTIALS: /etc/42/deepthought-dev.json
  # Choose only one model provider...
  MODEL_PROVIDER: vertex
  # MODEL_PROVIDER: openai
  EMBEDDING_MODEL_NAME: all-MiniLM-L6-v2
  LOG_LEVEL: DEBUG
  COLLECTION_NAME: demo_collection
  OPENAI_MODEL_NAME: gpt-3.5-turbo
  VERTEX_REGION: us-central1
  VERTEX_ENDPOINT: us-central1-aiplatform.googleapis.com
  DISABLE_SWAGGER: 'false'
  SPEND_LOG_FILE: spend.log
  TOKENIZERS_PARALLELISM: 'false'
  APP_FILE: src/app.py
  SPEND_LIMIT: '0.075'
  CORS_ORIGINS: '*'
  VERTEX_PROJECT_ID: shadowbot-hgerlach
  VERTEX_MODEL_NAME: text-bison
  ### OpenAPI Spec ###
  API_TITLE: 'Deep Thought'
  API_VERSION: 0.1.0
  API_DESCRIPTION: 'Deep Thought API'
  SPEC_KEYS_TO_IGNORE: 'components,paths,info,'


# oc apply -f configmap.yaml -n admin-devspaces
# oc label configmap deep-thought-config controller.devfile.io/mount-to-devworkspace=true controller.devfile.io/watch-configmap=true
# oc annotate configmap deep-thought-config controller.devfile.io/mount-as=env
