kind: Secret
apiVersion: v1
metadata:
  name: google-application-credentials
  # namespace: deep-thought-dev
  annotations:
    controller.devfile.io/mount-path: /etc/42
    controller.devfile.io/mount-as: file
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  deepthought-dev.json: INSERT_JSON # insert deep thought json file. This current resides in /etc/innovation-office/deepthought/deepthought-local.json
type: Opaque

# oc apply -f google-application-credentials.yaml -n admin-devspaces
# oc label secret google-application-credentials controller.devfile.io/mount-to-devworkspace=true controller.devfile.io/watch-secret=true
# oc annotate secret google-application-credentials controller.devfile.io/mount-path="/etc/42"
