kind: Service
apiVersion: v1
metadata:
  name: deep-thought
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  # selector:
  #   app: deep-thought
  #   deployment: deep-thought
