kind: ConfigMap
apiVersion: v1
metadata:
  name: deep-thought-config
data:
  PYTHONPATH: /
  SPENDING_WARNING_PCT: '0.8'
  OPENAI_MODEL_PRICE: '0.000003'
  VERTEX_MODEL_VERSION: v1
  GOOGLE_APPLICATION_CREDENTIALS: DEAFULT_PATH
  MODEL_PROVIDER: AI_PROVIDER
  EMBEDDING_MODEL_NAME: EMBEDDING_MODEL_NAME
  LOG_LEVEL: DEBUG
  COLLECTION_NAME: YOUR_COLLECTION_NAME
  OPENAI_MODEL_NAME: OPENAI_MODEL_NAME
  VERTEX_REGION: VERTEXT_REGION
  VERTEX_ENDPOINT: VERTEX_ENDPOINT
  DISABLE_SWAGGER: 'false'
  SPEND_LOG_FILE: spend.log
  TOKENIZERS_PARALLELISM: 'false'
  APP_FILE: src/app.py
  SPEND_LIMIT: '0.075'
  CORS_ORIGINS: '*'
  VERTEX_PROJECT_ID: VERTEX_PROJECT_ID
  VERTEX_MODEL_NAME: VERTEX_MODEL_NAME
  API_TITLE: API_TITLE_FOR_SWAGGER
  API_VERSION: API_VERSION_FOR_SWAGGER
  API_DESCRIPTION: API_DESCRIPTION_FOR_SWAGGER
  SPEC_KEYS_TO_IGNORE: 'components,paths,info,'
