name: Deploy to OpenShift

on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "Makefile"
      - "pyproject.toml"
      - "poetry.lock"
      - "deployment/**"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: ${{ secrets.OPENSHIFT_PROJECT_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest OpenShift CLI
        run: |
          curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.13.13.tar.gz"
          tar -xzvf openshift-client-linux-4.13.13.tar.gz
          sudo mv oc /usr/local/bin/oc
          oc version

      - name: Login to OpenShift Cluster
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER_URL }} --token=${{ secrets.OPENSHIFT_API_TOKEN }} --insecure-skip-tls-verify=true

      - name: Change deploy script permissions
        run: |
          chmod +x ./deployment/deploy.sh

      - name: Deploy to OpenShift
        run: |
          ./deployment/deploy.sh
